apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler-prometheus-discovery
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
    expose:  "{{ .Values.prometheusK8sServices.expose }}"
spec:
  selector:
    k8s-app: kube-scheduler
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10251
    targetPort: 10251
    protocol: TCP
