{{- if .Values.prometheusK8sServices.useOpenShift }}
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-controllers
  name: kube-controllers
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8444
    targetPort: 8444
  selector:
    openshift.io/component: controllers
    openshift.io/control-plane: "true"
{{- end }}