apiVersion: v1
name: prometheus-k8s-services
description: prometheus-k8s-services chart that runs on kubernetes
version: 1.0.8
keywords:
  - prometheus-k8s-services
  - kubernetes
home: https://github.com/stakater-charts/prometheus-k8s-services
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
