apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-dns-prometheus-discovery
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
    expose:  "{{ .Values.k8sServices.expose }}"
spec:
  selector:
{{ include "labels.selector" . | indent 4 }}
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics-skydns
    port: 10055
    targetPort: 10055
    protocol: TCP
  - name: http-metrics-dnsmasq
    port: 10054
    targetPort: 10054
    protocol: TCP
